name: aec-2024-skill08-s3-prod

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    image: ghcr.io/blz-it/aec-2024-skill08-s3-api:main
    environment:
      DB_HOST: postgres
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg_data:
